spring:
  datasource:
    url:
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create


server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: [password]
    key-store-type: PKCS12
    key-alias: bootsecurity